version: '3.9'

services:
 
  db_project:
    image: postgres:16
    container_name: db_postgres_project
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=qwerty1234
      - POSTGRES_USER=theivlev
      - POSTGRES_DB=project_collection
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

