version: '3.9'

services:
 
  db_auth:
    image: postgres:16
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=server_collection
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

